# Generated by Django 4.0.2 on 2022-02-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_balance',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
