# Generated by Django 4.0.2 on 2022-02-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_account_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='successful',
            field=models.BooleanField(default=False),
        ),
    ]
